[theme]
primaryColor="#0077b6"
backgroundColor="#e6f7ff"
secondaryBackgroundColor="#f8fcff"
textColor="#2c3e50"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true

[browser]
gatherUsageStats = false
